//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoHang
    {
        public int MaGH { get; set; }
        public int MaHD { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChi { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
