//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapSanPham
    {
        public int MaNhap { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<long> DonGia { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<long> TongTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
