//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKe
    {
        public int MaThongKe { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Ngay { get; set; }
        public Nullable<int> SoLuongBanRa { get; set; }
        public Nullable<int> SoLuongNhapVao { get; set; }
        public Nullable<long> TongThu { get; set; }
        public Nullable<long> TongChi { get; set; }
        public Nullable<long> LoiNhuan { get; set; }
    }
}
